base_url: "https://www.saucedemo.com/"
browser: "chrome"
timeout: 10
username: "standard_user"
password: "secret_sauce"

invalid_username: "invalid_user"
invalid_password: "wrong_password"

product_name: "Sauce Labs Backpack"
